### ISSUE TITLE
opam release with optional caml4p

### ISSUE THREAD

**Issue by brendanlong** [vbmithr/ocaml-text#4]
Would it be possible to do another opam release? We're using this library to do conversion between CP1252 and UTF-8, but the caml4p dependency is causing problems for us on OCaml 4.09 and 4.10. It looks like that was made optional in https://github.com/vbmithr/ocaml-text/commit/abf9b3d5e9192147a796ed1f2c0a4d313c75682c but it's not available in opam.

**Comment by vbmithr** [comment]
This is really ancient code, if you could try the [uu*] packages for unicode at https://erratique.ch/software, it would be much better as those will be supported.

**Comment by vbmithr** [comment]
But sure for a quick release without camlp4 I can do that.

**Comment by brendanlong** [comment]
Unfortunately Uutf doesn't support CP1252 :( At some point we might try contributing more codecs to that library or making a basic UTF-8 <-> CP1252 converter but Text really is basically what we want.

**Comment by brendanlong** [comment]
Thanks! https://opam.ocaml.org/packages/text/text.0.8.1/
